<div id="header">
    <h1>
        Site name
    </h1>
    <div style="float: right;">
        <?php if ($this->admin == 'khurram') { ?>
            Welcome:<b> <?php echo $this->admin; ?></b> | <a href="<?php echo $this->url(array('controller' => 'authentication', 'action' => 'logout')); ?>">Logout</a>
        <?php
        } else {
            echo "Please Login";
        }
        ?>
    </div>
</div>
