<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>   
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css'); ?>
    </head>
    <body>
        <div id="wrapper">

            <!-- header -->
            <div id="header">
                <div class="topbar a-right">
                    <ul class="hor-list-basic">
                        <li>
                            <span class="txt-litegray11">SHOPPING CART</span>
                        </li>
                        <li>
                            <span class="txt-litegray11"><strong>(0)</strong></span>
                        </li>
                        <li>
                            <a href="#"><img src="images/icon-cart.png" width="32" height="24" border="0" /></a>
                        </li>
                    </ul>

                    <div class="c-left">
                    </div>

                </div>

                <div class="clear">
                </div>

                <div class="menubar">

                    <div class="logo a-left">
                        <a href="#"><img src="images/logo.png" width="139" height="37"  border="0"/></a>
                    </div>

                    <div id="menu" class="a-left">
                        <ul class="menu-list">
                            <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>MEN</strong></a></span></div></li>
                            <li><span class="txt-blue24">|</span></li>
                            <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>WOMEN</strong></a></span></div></li>
                            <li><span class="txt-blue24">|</span></li>
                            <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>KIDS</strong></a></span></div></li>
                            <li><span class="txt-blue24">|</span></li>
                            <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>ABOUT</strong></a></span></div></li>
                        </ul>
                    </div>

                    <div id="searchbox" class="a-right">

                        <div id="searchicon" class="a-right"> 
                            <a href="#"><img src="images/icon-search.png" width="14" height="14" border="0" /></a>
                        </div>

                        <div class="a-left">
                            <input name="" type="text" class="search-input" value="search" />
                        </div>

                        <div class="clear">
                        </div>
                    </div>

                    <div id="loginbox" class="a-right">
                        <ul class="menu-list">
                            <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>Register</strong></a></span></div></li>
                            <li><span class="txt-gray24">|</span></li>
                            <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>Login</strong></a></span></div></li>
                        </ul>
                    </div>



                </div>

            </div>
            <!-- header ends-->

            <?php echo $this->layout()->content; ?>
            <!-- footer -->


            <div id="footer">

                <div class="left">
                    <ul class="menu-list">
                        <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>My Account</strong></a></span></div></li>
                        <li><span class="txt-blue24">|</span></li>
                        <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>FAQs</strong></a></span></div></li>
                        <li><span class="txt-blue24">|</span></li>
                        <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>Terms</strong></a></span></div></li>
                        <li><span class="txt-blue24">|</span></li>
                        <li><div class="pad10top"><span class="txt-litegray12"><a href="#"><strong>Contact Us</strong></a></span></div></li>
                    </ul>
                </div>

                <div class="a-right">
                    <img src="images/socialstrip.png" width="168" height="23" />
                </div>

                <div class="clear">
                </div>

            </div>

            <!-- footer ends-->
        </div>
    </body>
</html>